##########################################################################
###			SAMPLE PROCESS FILE
### 			Version v1.0.0
##########################################################################

#States names can contain only alphabet and numeric characters
[states]
CheckAction

END
StartScript=(spawn)PowerShell.exe bin\\MOCK.ps1 "<Action>" "<username>" "<address>"
SendCurrentPassword=<pmpass>
SendNewPassword=<pmnewpass>
FAILLogon=FAIL(Login request failed, 8001)
[transitions]
#CurrentState		        Condition		   	             NextState
#------------		        ----------------	   	       -------------- 
CheckAction,                    	ActionIsVerify,                 StartScript
StartScript, 				CurrentPasswordInput,		SendCurrentPassword
SendCurrentPassword,			SuccessVerify,			END
SendCurrentPassword, 			ErrLoginFailed,			FAILLogon

CheckAction,				ActionIsChange,			StartScript
StartScript, 				CurrentPasswordInput,		SendCurrentPassword
SendCurrentPassword, 			ErrLoginFailed,			FAILLogon
SendCurrentPassword,			SendNewPasswordInput, 		SendNewPassword,
SendNewPassword,			SuccessChange,			END
SendNewPassword,			ErrLoginFailed,			FAILLogon
[CPM Parameters Validation]
username, source=FILE, Mandatory=yes
address, source=FILE, Mandatory=yes
pmnewpass, source=ENV, Mandatory=yes
pmpass, source=ENV, Mandatory=yes

[parameters]
PromptTimeout=60
SendSlow=1 .001
#SendHuman=.1 .3 1 .05 2

[Debug Information]
DebugLogFullParsingInfo=yes
DebugLogFullExecutionInfo=yes
DebugLogDetailBuiltInActions=yes
ExpectLog=yes
ConsoleOutput=no