##########################################################################
###			MFT PROMPTS FILE
### 			Version v11.20192309.09
##########################################################################

[conditions]

ErrLoginFailed=.*Login request failed.*
CurrentUsernameInput=.*Enter current username.*
CurrentPasswordInput=.*Enter current password.*
SendNewPasswordInput=.*Enter new password.*
SuccessChange=.*Password updated successfully.*
SuccessVerify=.*Password Verified successfully.*
TRUE=(expression)true
ActionIsLogon=(expression)[string equal -nocase "<action>" "logon"]
ActionIsChange=(expression)[string equal -nocase "<action>" "changepass"]
ActionIsVerify=(expression)[string equal -nocase "<action>" "verifypass"]
